seed: 0
dataloaders:
  _target_: training.build_dataloaders
  dataset:
    _target_: dataset.SupervisedGraphDataset
    data_path: /scratch/work/masooda1/datasets/downstream_datasets/DILI/DILI_Goldstandard_1111.csv
    cmpd_col: protonated_smiles_r
    label_col: TOXICITY
    cmpd_col_is_inchikey: false
    pad_length: 250
  train_size: 0.8
  val_size: 0.2
  test_size: 0.0
  split_method: butina
  butina_threshold: 0.7
  seed: 0
  batch_size: 32
  num_workers: 1
  pin_memory: true

model:
  _target_: model.LightningGGNN.load_from_checkpoint
  _args_:
  - # Path to extracted molecular encoder checkpoint (will be set via command line)
  strict: false
  n_edge: 1
  in_dim: 75
  n_conv: 6
  fc_dims:
  - 1024
  - 128
  - 1  # DILI is binary classification (toxic vs non-toxic)
  p_dropout: 0.1
  freeze: false  # For linear evaluation, freeze the pretrained weights

optimizer:
  _target_: torch.optim.AdamW
  lr:
  weight_decay:


scheduler:
  _target_: cosine_annealing_warmup.scheduler.CosineAnnealingWarmupRestarts
  first_cycle_steps: 50
  cycle_mult: 1
  max_lr: 
  min_lr: 1.0e-08
  warmup_steps: 10

scheduler_config:
  monitor: val/auprc_mean
  frequency: 1
  interval: epoch

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  num_nodes: 1
  precision: 32
  max_epochs: 100
  min_epochs: 50
  fast_dev_run: false
  check_val_every_n_epoch: 1
  callbacks:
  - _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: val/auprc_mean
    mode: max
    patience: 100
    verbose: true
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/auprc_mean
    mode: max
    save_top_k: 1
    dirpath: # Will be set via command line
    filename: "best-epoch-{epoch}-val_auprc-{val/auprc_mean:.3f}"
    save_last: true
    auto_insert_metric_name: false
  logger:
    _target_: pytorch_lightning.loggers.NeptuneLogger
    project: # Will be set via command line
    name: # Will be set via command line
    api_key: # Will be set via command line
    log_model_checkpoints: false

test_model:
  _target_: model.LightningGGNN.load_from_checkpoint
  checkpoint_path: # Will be set via command line
  n_edge: ${model.n_edge}
  in_dim: ${model.in_dim}
  n_conv: ${model.n_conv}
  fc_dims: ${model.fc_dims}
  p_dropout: ${model.p_dropout}

test_results_dir: # This will be overridden by the command line argument
test_results_filename: # This will be overridden by the command line argument
